apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  # postgres
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_DATA: "${POSTGRES_DATA}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hapi-config
data:
  # hapi
  HAPI_SERVER_PORT: "${HAPI_SERVER_PORT}"
  HAPI_SERVER_ADDRESS: "${HAPI_SERVER_ADDRESS}"
  HAPI_NETWORK_API: "${HAPI_NETWORK_API}"
  HAPI_NETWORK_CHAIN_ID: "${HAPI_NETWORK_CHAIN_ID}"
  HAPI_HASURA_URL: "${HAPI_HASURA_URL}"
  HAPI_HASURA_ADMIN_SECRET: "${HAPI_HASURA_ADMIN_SECRET}"
  HAPI_EDENSMARTPRX_CONTRACT: "${HAPI_EDENSMARTPRX_CONTRACT}"
  HAPI_EDEN_CONTRACT: "${HAPI_EDEN_CONTRACT}"
  HAPI_AA_BASE_URL: "${HAPI_AA_BASE_URL}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-config
data:
  # hasura
  HASURA_GRAPHQL_ENABLE_CONSOLE: "${HASURA_GRAPHQL_ENABLE_CONSOLE}"
  HASURA_GRAPHQL_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL}"
  HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}"
  HASURA_GRAPHQL_ACTION_BASE_URL: "${HASURA_GRAPHQL_ACTION_BASE_URL}"
